### ISSUE TITLE
Export reference frame no errors, but nothing shows up

### ISSUE THREAD

**Issue by osvaldo14** [mm-89/InExEs#5]
Gui button works fine and code seems to be executed, but nothing shows up like the show mesh btn

**Comment by mm-89** [comment]
Try to change the normalization_factor in "shared_parameters" to 1e-6 or lower

**Comment by osvaldo14** [comment]
My bad, I thought  that a mesh will be showed up with the function trimesh.show(), but not in my version so the code work correctly and the file is created in the output folder 👍
